name = "DN1"
uuid = "f0cfa349-733a-4c46-aa1e-e7e789a16929"
authors = ["Martin StariÄ <96232207+SpongeMartin@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
